In [3]:
!pip install scikit-learn

   ---------------------------------------- 0.0/11.1 MB ? eta -:--:--
    --------------------------------------- 0.3/11.1 MB ? eta -:--:--
   ----- ---------------------------------- 1.6/11.1 MB 4.9 MB/s eta 0:00:02
   --------- ------------------------------ 2.6/11.1 MB 4.8 MB/s eta 0:00:02
   -------------- ------------------------- 3.9/11.1 MB 5.3 MB/s eta 0:00:02
   ------------------- -------------------- 5.5/11.1 MB 5.7 MB/s eta 0:00:01
   ------------------------ --------------- 6.8/11.1 MB 5.9 MB/s eta 0:00:01
   ----------------------------- ---------- 8.1/11.1 MB 6.1 MB/s eta 0:00:01
   --------------------------------- ------ 9.2/11.1 MB 5.7 MB/s eta 0:00:01
   ----------------------------------- ---- 10.0/11.1 MB 5.8 MB/s eta 0:00:01
   ---------------------------------------  11.0/11.1 MB 5.7 MB/s eta 0:00:01
   ---------------------------------------- 11.1/11.1 MB 5.4 MB/s eta 0:00:00
   ---------------------------------------- 0.0/43.6 MB ? eta -:--:--
   - ------------

In [1]:
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeClassifier

In [2]:
my_data = pd.read_csv("drug200.csv")

In [3]:
my_data[0:5]

Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  drugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  drugY

In [4]:
x = my_data[['Age','Sex','BP','Cholesterol','Na_to_K']].values
x[0:5]

array([[23, 'F', 'HIGH', 'HIGH', 25.355],
       [47, 'M', 'LOW', 'HIGH', 13.093],
       [47, 'M', 'LOW', 'HIGH', 10.114],
       [28, 'F', 'NORMAL', 'HIGH', 7.798],
       [61, 'F', 'LOW', 'HIGH', 18.043]], dtype=object)

In [5]:
from sklearn import preprocessing
le_sex = preprocessing.LabelEncoder()
le_sex.fit(['F','M'])
x[:,1] = le_sex.transform(x[:,1])


In [6]:
x[0:5]

array([[23, 0, 'HIGH', 'HIGH', 25.355],
       [47, 1, 'LOW', 'HIGH', 13.093],
       [47, 1, 'LOW', 'HIGH', 10.114],
       [28, 0, 'NORMAL', 'HIGH', 7.798],
       [61, 0, 'LOW', 'HIGH', 18.043]], dtype=object)

In [7]:
le_BP = preprocessing.LabelEncoder()
le_BP.fit(['LOW','NORMAL','HIGH'])
x[:,2] = le_BP.transform(x[:,2])

In [8]:
x[0:5]

array([[23, 0, 0, 'HIGH', 25.355],
       [47, 1, 1, 'HIGH', 13.093],
       [47, 1, 1, 'HIGH', 10.114],
       [28, 0, 2, 'HIGH', 7.798],
       [61, 0, 1, 'HIGH', 18.043]], dtype=object)

In [9]:
le_Cholesterol = preprocessing.LabelEncoder()
le_Cholesterol.fit(['NORMAL','HIGH'])
x[:,3] = le_Cholesterol.transform(x[:,3])

In [10]:
x[0:5]

array([[23, 0, 0, 0, 25.355],
       [47, 1, 1, 0, 13.093],
       [47, 1, 1, 0, 10.114],
       [28, 0, 2, 0, 7.798],
       [61, 0, 1, 0, 18.043]], dtype=object)

In [11]:
y = my_data['Drug']
y[:10]

0    drugY
1    drugC
2    drugC
3    drugX
4    drugY
5    drugX
6    drugY
7    drugC
8    drugY
9    drugY
Name: Drug, dtype: object

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state =3)

In [14]:
drugtree = DecisionTreeClassifier(criterion="entropy" , max_depth = 4)
drugtree

DecisionTreeClassifier(criterion='entropy', max_depth=4)

In [15]:
drugtree.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=4)

In [16]:
predtree = drugtree.predict(x_test)

In [18]:
print (predtree [0:5])

['drugY' 'drugX' 'drugX' 'drugX' 'drugX']


In [19]:
print (y_test[0:5])

40     drugY
51     drugX
139    drugX
197    drugX
170    drugX
Name: Drug, dtype: object


In [21]:
from sklearn import metrics
print ("DecisionTree's Accuracy:",metrics.accuracy_score(y_test,predtree))

DecisionTree's Accuracy: 0.9833333333333333
